### ISSUE TITLE
Help with kit and custom kit usage. Not able to reclaim kits. running forge 1.16.1 - 32.0.98 latest to this date.

### ISSUE THREAD

**Issue by HulkBravo** [Maciej916/Ma-Essentials#69]
Hello, 

I need a little help to use the kits. So far, It seems like I only get a kit once, and only if the kit is set as starting kit when creating a new world, but after that I can´t re-claim any other kit nor the starting kit, even if delay time set to 100.

also, there is no msgs in-game about delay time to reclaim a kit in my tests.

running forge 1.16.1 - 32.0.98 test done in single player, and single player open to lan.
other mods running along are xaeros radar and world map only.

I tried using the default kit, and customized kit with no luck to reclaim a kit for both maessentials default kit file and a customized kit file I created.

My custom kit file runs valid on json parse, but as mentioned I can get the kit only once when creating a new world and not able to claim any other kit and neither reclaim the starting kit.

If you know how to help me to get the kits to work and be reclaimed, please post a msg.

Thanks for your attention.

**Comment by SDUBZ** [comment]
this seems to be happing with a few commands fly/ kits etc

**Comment by HulkBravo** [comment]
Downloaded v3.2.4 hoping kits would work as in the developer video, but nope, no luck. Starting kit works when created a new world and not once again. Still no msg in-game about delay till able to reclaim a kit again.

**Comment by SDUBZ** [comment]
Ma-Essentials-1.16.1-3.2.4 
Kits still bugged
both tools and enderchest
fly is working now

**Comment by Maciej916** [comment]
I'll look into it.

**Comment by Maciej916** [comment]
Fixed in [Ma-Essentials-1.16.1-3.2.5](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/3036605)

**Comment by HulkBravo** [comment]
the default kit works now and delay time displayed, but if create a new world it keeps the delay from previous world.

custom kits still not working

why did you close the issue? let me close the issue after testing, pls.
